const data = {
  blocks: [
    {
      key: "9jas9",
      text: "Infinitive and Aspect",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 21, style: "color-#ff8748" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "2ndkp",
      text: "The infinitive form of a verb, sometimes known as basic form or dictionary form, is the form a verb has before it is conjugated. ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 4, length: 10, style: "BOLD" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "50tfn",
      text: "To conjugate a verb means to change its form. In English, conjugating a verb can change its aspect, voice, mood, tense, person, number, gender etc. In Tagalog, conjugation only changes the aspect. Aspect indicates the state of completion of an action. There are three aspects that occur in all Tagalog verbs:",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 197, length: 6, style: "BOLD" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "dq037",
      text: "Completed aspect, sometimes known as perfective, indicates the action has been completed.",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 9, style: "BOLD" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "7vkn",
      text: "Uncompleted aspect, sometimes known as imperfective, incompleted or habitual, indicates the action has started but has not been completed.",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 11, style: "BOLD" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "3hopj",
      text: "Contemplated aspect, sometimes known as unstarted, indicates the action has not yet begun.",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 12, style: "BOLD" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "2fgt6",
      text: "Note – there is another aspect, the recently completed, that occurs in certain verbs, but it is much less common and will not be covered in this book.",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "ghg6",
      text: "Here are some examples for the infinitive mag-aral (to study).",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 42, length: 8, style: "ITALIC" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "c9621",
      text: "Ex: Nag-aral si Maria ng Tagalog. = Maria studied Tagalog. Nag-aral (studied) is completed aspect; the studying has been completed.  ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 59, length: 8, style: "ITALIC" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "fmp7a",
      text: "Ex: Nag-aaral si Maria ng Tagalog. = Maria is/was studying Tagalog (or Maria studies Tagalog, depending on context). Nag-aaral (studying/studies) is uncompleted aspect; the studying has started but has not been completed. ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 117, length: 9, style: "ITALIC" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "7gm2a",
      text: "Ex: Mag-aaral si Maria ng Tagalog. = Maria will study Tagalog (or Maria will be studying Tagalog, depending on context). Mag-aaral (will study/will be studying) is contemplated aspect; the studying has not yet begun.  ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 121, length: 9, style: "ITALIC" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "2rbdk",
      text: "Aspect vs Tense",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 15, style: "color-#ff8748" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "2cj2a",
      text: "At first glance, it may appear that the three aspects are just the past, present and future tenses. So why not just call them tenses and be done with it? Because they are not equivalent. Compare the following Tagalog sentence with its possible English definitions: ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "9mgo9",
      text: "Ex: Nag-aaral si Maria ng Tagalog. (Tagalog Uncompleted Aspect)",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "9s1a6",
      text: "Ex: Maria studies Tagalog. (English Present Simple Tense)",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "3ngbk",
      text: "Ex: Maria is studying Tagalog. (English Present Continuous Tense)",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "5k68p",
      text: "Ex: Maria was studying Tagalog. (English Past Continuous Tense)",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "1lrn0",
      text: "For Tagalog one aspect is used, while in English three tenses are used. That is an example of why we say “aspect” rather than “tense” in this book. Most learning materials call them aspects, but be aware that some learning materials, teachers and native speakers call them tenses. ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "7itm0",
      text: "Sample Conjugation Table",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 24, style: "color-#ff8748" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "9qkks",
      text: " ",
      type: "atomic",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [{ offset: 0, length: 1, key: 0 }],
      data: {},
    },
    {
      key: "7j075",
      text: "It may help to visualize this table when thinking about aspect. Table 1 lists the infinitive and three aspects of the verb mag-aral. This is just a sample; different verb types are conjugated differently, as you will learn in the lessons. ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [{ offset: 123, length: 8, style: "ITALIC" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "e0nbk",
      text: "Frequency of Infinitives and Aspects",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [{ offset: 0, length: 36, style: "color-#ff8748" }],
      entityRanges: [],
      data: {},
    },
    {
      key: "abhag",
      text: " ",
      type: "atomic",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [{ offset: 0, length: 1, key: 1 }],
      data: {},
    },
    {
      key: "9qete",
      text: "",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "bqs3c",
      text: "",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "q5if",
      text: "This table was included for those curious to know how frequently the different verb forms occur in colloquial speech.",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "7ive4",
      text: "",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
  ],
  entityMap: {
    0: {
      type: "HTML",
      mutability: "MUTABLE",
      data: {
        html: '\n\n\n<table width="422" class="MsoNormalTable table table-success w-50">\n <tr>\n  <td class="text-nowrap" width="120">\n  <b>Form</b>\n  </td>\n  <td class="text-nowrap" width="84">\n  <b>Verb</b>\n  </td>\n  <td class="text-nowrap" colspan="2" width="218">\n  <b>Definition</b>\n  </td>\n </tr>\n <tr>\n  <td class="text-nowrap" width="120">\n  infinitive\n  </td>\n  <td class="text-nowrap" width="84">\n  mag-aral\n  </td>\n  <td class="text-nowrap" width="84">\n  to study\n  </td>\n  <td class="text-nowrap" width="134">\n  study\n  </td>\n </tr>\n <tr>\n  <td class="text-nowrap" width="120">\n  completed\n  </td>\n  <td class="text-nowrap" width="84">\n  nag-aral\n  </td>\n  <td class="text-nowrap" colspan="2" width="218">\n  studied\n  </td>\n </tr>\n <tr>\n  <td class="text-nowrap" width="120">\n  uncompleted\n  </td>\n  <td class="text-nowrap" width="84">\n  nag-aaral\n  </td>\n  <td class="text-nowrap" width="84">\n  studying\n  </td>\n  <td class="text-nowrap" width="134">\n  studies\n  </td>\n </tr>\n <tr>\n  <td class="text-nowrap" width="120">\n  contemplated\n  </td>\n  <td class="text-nowrap" width="84">\n  mag-aaral\n  </td>\n  <td class="text-nowrap" width="84">\n  will study\n  </td>\n  <td class="text-nowrap" width="134">\n  will be studying\n  </td>\n </tr>\n <tr>\n  <td class="text-nowrap" colspan="4" width="422">\n  <b>Table 1: Infinitive and\n  Aspects </b>\n  </td>\n </tr>\n</table>\n\n\n\n\n\n',
      },
    },
    1: {
      type: "HTML",
      mutability: "MUTABLE",
      data: {
        html: '<table class="table table-success"><colgroup width="139"></colgroup><colgroup width="118"></colgroup><tr><td align="center"><b>Form</b></td><td align="center"><b>Usage</b></td></tr><tr><td align="center">infinitive</td><td align="center">33%</td></tr><tr><td align="center">completed</td><td align="center">24%</td></tr><tr><td align="center">uncompleted</td><td align="center">26%</td></tr><tr><td align="center">contemplated</td><td align="center">17%</td></tr><tr><td align="center" colspan="2"><b>Table 2: Usage of Infinitive and Aspects in Colloquial Speech. (Source: Language Tools Tagalog Conversations) </b></td></tr></table>',
      },
    },
  },
};

console.log(data);
